### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  

### ISSUE THREAD

**Issue by brulser** [jwoolston/Android-Libusb-Wrapper#16]
i need study this for my job.download your project ,build this project, Android Studio  show **CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.** 
i add Ninja  in SDK /Cmake /**/bin to path.but show same error ，could you help  me or show solution to me! 
--that's very nice of you!

**Comment by jwoolston** [comment]
Closing this issue as invalid/wontfix. This appears to be a problem with your setup of the Android SDK.
