### ISSUE TITLE
example to start ? 

### ISSUE THREAD

**Issue by Chakib-Temal** [jwoolston/Android-Libusb-Wrapper#29]
i wanna to try your library Java android 

building : 
Due to the NDK requirement, building this project will require you to have the Android NDK on your machine. Setup of the NDK is left to the user. See Google's NDK website for more information on this.

After setting up the NDK, you will need to reference it in your version of local.properties by declaring ndk.dir.

Following this, the project should build successfully.

OK , but what's the next step ? did you have an example to follow ? 
or i should compile your project after building my ndk ? 
thank you

**Comment by jwoolston** [comment]
You should not need to build the NDK, it is a tool distribution available through the Android SDK. If you have it available, the project will build through Gradle like any other android library/app.

**Comment by MontyYan** [comment]
How to use it？import into my project?

**Comment by jwoolston** [comment]
At the moment I have not gotten around to getting it properly published. As such, you will have to build a jar and include it manually or publish it to your own maven repo (either local or a private hosted one). The precise mechanics of each are highly dependent on your environment and outside the scope of what I can assist with.
